# Override file for environment-specific configuration
# This file overrides the base docker-compose.yaml with Komodo environment variables

services:
  op-connect-api:
      volumes:
        # Remove the credentials file mount by explicitly setting volumes
        - "op-connect-data:/home/opuser/.op/data"
      environment:
        # Override to use Base64-encoded credentials from Komodo variable
        OP_SESSION: "[[OP_CREDENTIALS_BASE64]]"
  op-connect-sync:
      volumes:
        # Remove the credentials file mount by explicitly setting volumes
        - "op-connect-data:/home/opuser/.op/data"
      environment:
        # Override to use Base64-encoded credentials from Komodo variable
        OP_SESSION: "[[OP_CREDENTIALS_BASE64]]"
  komodo-op:
    environment: !override
      # Override with actual Komodo configuration
      KOMODO_HOST: "${KOMODO_HOST}"
      KOMODO_API_KEY: "${KOMODO_API_KEY}"
      KOMODO_API_SECRET: "${KOMODO_API_SECRET}"
      OP_SERVICE_ACCOUNT_TOKEN: "${OP_SERVICE_ACCOUNT_TOKEN}"
      OP_VAULT: "${OP_VAULT}"
      SYNC_INTERVAL: "${SYNC_INTERVAL:-30s}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      # OP_CONNECT_HOST is fine as-is since it's internal Docker networking